[package]
name = "robius-android-env"
version = "0.1.0"
edition = "2021"

[dependencies]
jni = "0.21.1"
makepad-android-state = { version = "0.1.0", optional = true }

[features]
## Set this feature when building a Makepad app.
makepad = ["dep:makepad-android-state"]
